export const SET_CURRENCIES = "SET_CURRENCIES";
export const SET_LOADING_CURRENCIES = 'SET_LOADING_CURRENCIES'
export const SET_LAST_UPDATE = 'SET_LAST_UPDATE'
export const SET_FAVORITE_CURRENCY = 'SET_FAVORITE_CURRENCY'
export const REMOVE_FAVORITE_CURRENCY = 'REMOVE_FAVORITE_CURRENCY'